package springboot.start.db.company2.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import springboot.start.db.company2.pojo.TSubject;
import springboot.start.db.company2.pojo.TSubjectExample;

public interface TSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbggenerated
     */
    int countByExample(TSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbggenerated
     */
    int deleteByExample(TSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbggenerated
     */
    int insert(TSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbggenerated
     */
    int insertSelective(TSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbggenerated
     */
    List<TSubject> selectByExample(TSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TSubject record, @Param("example") TSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TSubject record, @Param("example") TSubjectExample example);
}