package springboot.start.db.company2.pojo;

public class TSubject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.subid
     *
     * @mbggenerated
     */
    private Integer subid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.subname
     *
     * @mbggenerated
     */
    private String subname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.subid
     *
     * @return the value of t_subject.subid
     *
     * @mbggenerated
     */
    public Integer getSubid() {
        return subid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.subid
     *
     * @param subid the value for t_subject.subid
     *
     * @mbggenerated
     */
    public void setSubid(Integer subid) {
        this.subid = subid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.subname
     *
     * @return the value of t_subject.subname
     *
     * @mbggenerated
     */
    public String getSubname() {
        return subname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.subname
     *
     * @param subname the value for t_subject.subname
     *
     * @mbggenerated
     */
    public void setSubname(String subname) {
        this.subname = subname == null ? null : subname.trim();
    }
}